hamster:
  match:
    - 'automated'
    - 'hamster'
    - 'hamster-bot'
  description: 'Its my hamster.'

feat:
  match:
    - 'feature'
    - 'feat'
    - 'src'
  description: 'Feature or enhancement.'

boss:
  match:
    - 'admin'
    - 'boss'
  description: 'Its me (boss).'

testing:
  match:
    - 'testing'
    - 'wip'
    - 'incomplete'
    - 'local'
  description: 'Testing for bugs or issues.'