kind/docker:
  match:
    - 'Dockerfile'
  description: 'Relating to docker runtime.'
  
kind/javascript:
  match:
    - '**/*.jsx' 
    - '**/*.js' 
  description: 'Changes Javascript files'

kind/ci:
  match:
    - '**/*.yml'
    - '**/*.yaml'
    - 'Dockerfile'
  description: 'Changes CI/CD files'

kind/html:
  match:
    - '**/*.html'
    - '**/*.css'
  description: 'Changes html or css files'
  
bot/hamster:
  match:
    - 'automated'
    - 'hamster'
  description: 'Thats my hamster'

kind/assets:
  match:
    - 'public/**/*'
    - '**/assets/**/*'
  description: 'Changes Static Assets'

kind/configuration:
  match:
    - 'Dockerfile'
    - '.gitignore'
    - '**/*.yaml'
    - '**/*.json'
    - 'treemap'
  description: 'Changes dotfiles'

kind/deno:
  match:
    - 'deno.json'
  description: 'Deno configuration'