name: CI / Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  upgrade-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm@v10
        uses: pnpm/action-setup@v4
        with:
          version: 10.0.0

      - name: Install & Upgrade Dependencies
        run: |
          pnpm install
          pnpm update
          pnpm install --lockfile-only

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          delete-branch: true
          token: ${{ secrets.BOT_TOKEN }}
          committer: 'Hamster [bot] <TheHamsterBot@outlook.com>'
          author: 'Hamster [bot] <TheHamsterBot@outlook.com>'
          branch: 'update-weekly-dependencies'
          base: 'master'
          labels: |
            hamster
            dependencies
          reviewers: offensive-vk
          commit-message: 'Update Dependencies - package.json'
          title: '🐹 Update Project Root Dependencies'
          body: |
            ## Updated all Dependencies to Latest Point Release.

            > [!IMPORTANT]
            > This PR Updates the Dependencies
            >
            > Commit: ${{ github.sha }}
            > Workflow Name: ${{ github.workflow }}
            > Workflow Path: ${{ github.workflow_ref }}

            Please Check the Dependency Updates Below and merge if necessary.

            ---

            Thanks.
            Your Hamster 🐹 <code>PF78VAPPKLZ2</code>